module.exports = {
    purge: {
        enabled: process.env.ENV === 'production',
        content: [
            'components/**/*.vue',
            'layouts/**/*.vue',
            'pages/**/*.vue',
            'plugins/**/*.js',
            'nuxt.config.js',
        ],
    },
    theme: {
        extend: {
            spacing: {
                72: '18rem',
                84: '21rem',
                96: '24rem',
            },
            width: {
                '1/8': '12.5%',
                '1/6': '16.77%',
                '1/5': '20%',
                '1/4': '25%',
                '1/3': '33.33%',
                '1/2': '50%',
                '2/5': '40%',
                '4/5': '80%',
                '9/10': '90%',
                '3/4': '75%',
                '3/10': '30%',
                '5/6': '83.33%',
                '1/10': '10%',
                '1/20': '5%',
                '7/10': '70%',
            },
            inset: {
                8: '2rem',
                12: '3rem',
                16: '4rem',
            },
            opacity: {
                0: 0,
                10: '0.1',
            },
        },
        minHeight: {
            0: '0',
            '1/8': '12.5%',
            '1/6': '16.77%',
            '1/5': '20%',
            '1/4': '25%',
            '1/3': '33.33%',
            '1/2': '50%',
            '2/5': '40%',
            '4/5': '80%',
            '9/10': '90%',
            '3/4': '75%',
            '3/10': '30%',
        },
        borderColor: theme => ({
            web: '#efeff0',
        }),
        backgroundColor: theme => ({
            white: '#fff',
            web: '#F9F9F9',
        }),
        screens: {
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            'desktop-xs': '1366px',
            'desktop-md': '1440px',
            'desktop-lg': '1600px',
            'desktop-xl': '1920px',
        },
    },
};
